### ISSUE TITLE
`quarto_inspect()` gives weird error if directory ins't a quarto doc

### ISSUE THREAD

**Issue by hadley** [quarto-dev/quarto-r#104] opened 2023-05-03 14:49 UTC
```
> quarto::quarto_inspect()
ERROR: . is not a quarto project.
Error:
! lexical error: invalid char in json text.
                                       NA
                     (right here) ------^
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
In system2(quarto_bin, stdout = TRUE, c("inspect", path.expand(input))) :
  running command ''/usr/local/bin/quarto' inspect .' had status 1
```

Should ideally just be:

```
> quarto::quarto_inspect()
Error: '.' is not a quarto project.
```

**Comment by cderv** [comment] 2024-01-23 16:09
I think this has been fixed now that `quarto_run()` uses `processx::run()` and `rlang::abort()`

I get this 
````
> quarto_inspect()
Error in `quarto_inspect()`:
! Error running quarto cli:
✖ ERROR: . is not a quarto project.

Stack trace:
    at inspectConfig (file:///C:/Users/chris/scoop/apps/quarto-prerelease/current/bin/quarto.js:98722:19)
    at async Command.fn (file:///C:/Users/chris/scoop/apps/quarto-prerelease/current/bin/quarto.js:98776:20)
    at async Command.execute (file:///C:/Users/chris/scoop/apps/quarto-prerelease/current/bin/quarto.js:8104:13)
    at async quarto (file:///C:/Users/chris/scoop/apps/quarto-prerelease/current/bin/quarto.js:114968:5)
    at async file:///C:/Users/chris/scoop/apps/quarto-prerelease/current/bin/quarto.js:114986:9
Caused by error:
! System command 'quarto.exe' failed
Run `rlang::last_trace()` to see where the error occurred.

**Comment by cderv** [comment] 2024-01-23 19:05
Thanks for the feedback !

**Closed by cderv** 2024-01-23 19:05 UTC
