### ISSUE TITLE
Feature request: add envir argument in quarto_render()

### ISSUE THREAD

**Issue by matthewhirschey** [quarto-dev/quarto-r#29] opened 2022-07-29 17:12 UTC
- [ ] rmarkdown::render() has an envir var, which would be great to implement in quarto::quarto_render()

From render()
> envir	
> The environment in which the code chunks are to be evaluated during knitting (can use [new.env](http://127.0.0.1:54354/help/library/rmarkdown/help/new.env)() to guarantee an empty new environment).

Can this be done from quarto?

**Comment by cderv** [comment] 2022-07-29 19:30
Can you explain the use case behind it ? 

`rmarkdown::render` has this option because by default the rendering happens in the current R session, but setting `new.env()` allows to insure a clean new environment. 

With `quarto`, each R evaluation will happen in a clean environment. `quarto::quarto_render()` will call the the command line tool `quarto` from R and any R processing within quarto won't use the session from which the `quarto_render()` was called. 

I am not quite sure what is missing ? Did you encounter an environnement conflict somehow  ?

**Comment by matthewhirschey** [comment] 2022-07-30 10:43
Thanks for following up. When I looked into `quarto_render()`, I saw that it's a wrapper for accessing the command line `quarto` tool, hence asking about this in a "feature request", because it was non-obvious how/if this was possible.The use case is not because of an environment conflict, but instead because I'd like to force quarto to render in the global environment (not best practice, I know). 

I'm building a 'report generator'. This report generator will live in a stand-alone container, and wait for messages to build a report. Each report needs ~5GB of files loaded into the render environment, gets rendered, and then uses `blastula` to send it via email. Currently, it takes ~15 minutes to make a single report. With `rmarkdown`, I can load all of the objects into the global environment, and then tell rmarkdown to look there (basically override its default to create a new envir). If I could do this with `quarto`, then I wouldn't need to load all of the data for each report and instead only do it once. 

Of course, you might say "sounds like you might need to change your data engineering practices", and we are transitioning to some databases, etc. But even in the future, the redundancy of loading data into a clean session in an isolated environment would be great to override in `quarto`, as we can in `rmarkdown`.

**Comment by cderv** [comment] 2022-07-31 21:48
I need to look closer to your use case but **rmarkdown** is not working like **quarto** regarding **knitr** rendering. There won't be one global environment for all the chunk evaluation. Each document is evaluated on its own in a clean new session which is close after chunk evaluation. 

This means it is not as easy as passing a `envir` environment from `quarto_render` to `knitr::knit` - it does not work that way. 

Keeping R objects between files rendering is something that we will need to tackle somehow, either better document a workflow or come up with an API to help make that easier. 

Unfortunately for now, you need to change your workflow - Loading objects for each file is possible I guess (using .RData or explicitly in a setup chunk). But it seems your data is heavy / long to load. If so, you should target which data to load, or use some data storage that allows you to request which data is needed. Anyway, not the answer your need right now. 

I would sugget follow `quarto-cli` repo on this topic as this is definitely not an issue from the R package. `quarto render` would need to support that for project. 

See for example https://github.com/quarto-dev/quarto-cli/issues/1590 and linked issue.

**Comment by matthewhirschey** [comment] 2022-08-01 10:42
All makes sense. 
Thanks for taking the time to think through this with me. OK to close this "issue", and I'll keep an eye on the other quarto repos. 

🙏🏼

**Comment by kapsner** [comment] 2022-08-03 10:57
+1 Hi, I would also highly appreciate this feature. Before when using `rmarkdown::render_report`, it was possible to create objects in an R script and at the end of the script render the pdf using these objects (even if they were not created directly in the Rmd-file).

Switching to `quarto::quarto_render` I just encountered that this is not possbile anymore. It would be very helpful, if `quarto_render` would also consider objects from the environment it is called from, or alternatively, provide an argument that allows to pass objects on to the qmd-file.

**Comment by cderv** [comment] 2023-01-09 17:28
> Before when using rmarkdown::render_report, it was possible to create objects in an R script and at the end of the script render the pdf using these objects (even if they were not created directly in the Rmd-file).

Yes this is not possible with Quarto, because it is not implemented in R only like with **rmarkdown**. It is language agnostic, so if you need to create data before rendering your document, you either need to include the steps in a first chunk or run a script as a [pre render step](https://quarto.org/docs/projects/scripts.html#pre-and-post-render), save the results on disk, and load in your document 

> It would be very helpful, if quarto_render would also consider objects from the environment it is called from (or alternatively, provide an argument that allows to pass objects on to the qmd-file).

This is not to be considered as this is not possible by design. `quarto render` is run without knowledge of R or any other scientific environment. It will execute R as part of the rendering of computational cell. You can leverage R feature (like startup script for R process) maybe. 

Anyway, as suggested by @matthewhirschey, I'll close this and one should follow upstream https://github.com/quarto-dev/quarto-cli/issues/1590

Thanks

**Closed by cderv** 2023-01-09 17:28 UTC
Labels: enhancement
