### ISSUE TITLE
Format of HTML quarto presentation

### ISSUE THREAD

**Issue by lervin1** [quarto-dev/quarto-r#114] opened 2023-08-27 19:10 UTC
when I zip my folder and try to view the rendered HTML file for my quarto presentation, the format is off and it doesn't view like a presentation should. I have attached a ss of my file below is anyone can help.
![image](https://github.com/quarto-dev/quarto-r/assets/143349771/8d49882e-46b7-46db-8bec-9ce78a9d3c18)

My graphs are gone and it doesn't view in the slides presentation format like i want.

**Comment by cderv** [comment] 2023-08-30 09:43
This is a duplicate of 
* https://github.com/quarto-dev/quarto-cli/discussions/6632

I am closing to keep on discussion only

**Closed by cderv** 2023-08-30 09:43 UTC
